In [132]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    6 non-null      int64
 1   age            3 non-null      float64
 2   city           4 non-null      str
 3   gender         6 non-null      str
 4   annual_income  6 non-null      int64
dtypes: float64(1), int64(2), str(2)
memory usage: 372.0 bytes

In [134]:
impute_values = {
    'age': round(df['age'].mean(), 0),
    'city': df['city'].mode()[0]
}
df.fillna(impute_values, inplace=True)
df["age"] = round(df["age"]).astype(int)
df

   customer_id  age    city  gender  annual_income
0            1   25  Mumbai    Male          40000
1            2   33   Delhi  Female          80000
2            3   35   Delhi  Female          60000
3            4   33  Mumbai    Male         120000
4            2   33   Delhi  Female          80000
5            5   40   Delhi    Male          95000

In [135]:
df[df.duplicated()]

   customer_id  age   city  gender  annual_income
4            2   33  Delhi  Female          80000

In [136]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
df

   customer_id  age    city  gender  annual_income
0            1   25  Mumbai    Male          40000
1            2   33   Delhi  Female          80000
2            3   35   Delhi  Female          60000
3            4   33  Mumbai    Male         120000
4            5   40   Delhi    Male          95000

In [137]:
df = pd.get_dummies(df, columns=['city'])
df = pd.DataFrame(df)

In [138]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\sanja\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\sanja\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\sanja\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\sanja\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\sanja\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)

In [139]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [140]:
df["gender_encoded"] = le.fit_transform(df["gender"])
df.drop('gender', axis=1, inplace=True)

In [141]:
df

   customer_id  age  annual_income  city_Delhi  city_Mumbai  gender_encoded
0            1   25          40000       False         True               1
1            2   33          80000        True        False               0
2            3   35          60000        True        False               0
3            4   33         120000       False         True               1
4            5   40          95000        True        False               1

In [142]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [143]:
standard_copy = df.copy()

standard_copy[['age', 'annual_income']] = scaler.fit_transform(standard_copy[['age', 'annual_income']])
standard_copy

,customer_id,age,annual_income,city_Delhi,city_Mumbai,gender_encoded
0,1,-1.696592,-1.410970,False,True,1
1,2,-0.041380,0.036179,True,False,0
2,3,0.372423,-0.687396,True,False,0
3,4,-0.041380,1.483328,False,True,1
4,5,1.406930,0.578860,True,False,1

In [144]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()

In [145]:
minmax_copy = df.copy()
minmax_copy[['age', 'annual_income']] = minmax_scaler.fit_transform(minmax_copy[['age', 'annual_income']])
minmax_copy

,customer_id,age,annual_income,city_Delhi,city_Mumbai,gender_encoded
0,1,0.000000,0.0000,False,True,1
1,2,0.533333,0.5000,True,False,0
2,3,0.666667,0.2500,True,False,0
3,4,0.533333,1.0000,False,True,1
4,5,1.000000,0.6875,True,False,1

Standardization scales the data to have a mean of 0 and standard deviation of 1. It preserves the distribution of the data and very robust in handling outliers. Preferred to use when the algorithm is distance-based, data have outliers, and there is no requirement for range.

MinMax scaling scales the data between the range [0, 1]. It doesn't preserve the distribution of the data. Use cases include Linear/Statistical model, few/no outliers, when the scaled values need to be in a specific range.